// AUTO-GENERATED by scripts/generate-projects.mjs — do not edit by hand.
// Re-run after changing public/projects/:  node scripts/generate-projects.mjs

export type Project = {
  slug: string;
  title: string;
  category: string;
  description: string;
  cover: string;
  images: string[];
  videos: string[];
};

export const projects: Project[] = [
  {
    "slug": "recent-work",
    "title": "Recent Work",
    "category": "General",
    "description": "",
    "cover": "/projects/WhatsApp Image 2026-06-12 at 04.50.46.jpeg",
    "images": [
      "/projects/WhatsApp Image 2026-06-12 at 04.50.46.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.51.36.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.51.39.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.51.43.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.51.46.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.51.49.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.51.53.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.52.31 (1).jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.52.31.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.52.32.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.52.44.jpeg",
      "/projects/WhatsApp Image 2026-06-12 at 04.52.45.jpeg"
    ],
    "videos": [
      "/projects/WhatsApp Video 2026-06-12 at 04.50.27.mp4",
      "/projects/WhatsApp Video 2026-06-12 at 04.50.43.mp4"
    ]
  }
];

/** Unique categories present in the data, with "All" first (for filter chips). */
export const categories: string[] = [
  "All",
  ...Array.from(new Set(projects.map((p) => p.category))),
];
